/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutRoute } from './routes/_layout'
import { Route as ApiAuthProfileRoute } from './routes/api/auth/profile'
import { Route as ApiAuthMeRoute } from './routes/api/auth/me'
import { Route as ApiAuthLogoutRoute } from './routes/api/auth/logout'
import { Route as ApiAuthLoginRoute } from './routes/api/auth/login'
import { Route as ApiAuthRegisterRoute } from './routes/api/auth/register'
import { Route as LayoutProfileRoute } from './routes/_layout/profile'
import { Route as LayoutRegisterRoute } from './routes/_layout/register'
import { Route as LayoutLoginRoute } from './routes/_layout/login'
import { Route as LayoutDashboardRoute } from './routes/_layout/dashboard'
import { Route as LayoutIndexRoute } from './routes/_layout/index'

// Create/Update Routes

const ApiAuthProfileRouteWithChildren = ApiAuthProfileRoute

const ApiAuthMeRouteWithChildren = ApiAuthMeRoute

const ApiAuthLogoutRouteWithChildren = ApiAuthLogoutRoute

const ApiAuthLoginRouteWithChildren = ApiAuthLoginRoute

const ApiAuthRegisterRouteWithChildren = ApiAuthRegisterRoute

const LayoutProfileRouteWithChildren = LayoutProfileRoute

const LayoutRegisterRouteWithChildren = LayoutRegisterRoute

const LayoutLoginRouteWithChildren = LayoutLoginRoute

const LayoutDashboardRouteWithChildren = LayoutDashboardRoute

const LayoutIndexRouteWithChildren = LayoutIndexRoute

const LayoutRouteWithChildren = LayoutRoute._addFileChildren([
  LayoutIndexRouteWithChildren,
  LayoutDashboardRouteWithChildren,
  LayoutLoginRouteWithChildren,
  LayoutRegisterRouteWithChildren,
  LayoutProfileRouteWithChildren,
])

const rootRouteWithChildren = rootRoute._addFileChildren([
  LayoutRouteWithChildren,
  ApiAuthRegisterRouteWithChildren,
  ApiAuthLoginRouteWithChildren,
  ApiAuthLogoutRouteWithChildren,
  ApiAuthMeRouteWithChildren,
  ApiAuthProfileRouteWithChildren,
])

export interface FileRoutesByPath {
  '/': {
    id: '/'
    path: '/'
    fullPath: '/'
    preLoaderRoute: typeof LayoutIndexRouteWithChildren
    parentRoute: typeof LayoutRouteWithChildren
  }
  '/_layout': {
    id: '/_layout'
    path: '/'
    fullPath: '/'
    preLoaderRoute: typeof LayoutRouteWithChildren
    parentRoute: typeof rootRoute
  }
  '/dashboard': {
    id: '/dashboard'
    path: '/dashboard'
    fullPath: '/dashboard'
    preLoaderRoute: typeof LayoutDashboardRouteWithChildren
    parentRoute: typeof LayoutRouteWithChildren
  }
  '/login': {
    id: '/login'
    path: '/login'
    fullPath: '/login'
    preLoaderRoute: typeof LayoutLoginRouteWithChildren
    parentRoute: typeof LayoutRouteWithChildren
  }
  '/profile': {
    id: '/profile'
    path: '/profile'
    fullPath: '/profile'
    preLoaderRoute: typeof LayoutProfileRouteWithChildren
    parentRoute: typeof LayoutRouteWithChildren
  }
  '/register': {
    id: '/register'
    path: '/register'
    fullPath: '/register'
    preLoaderRoute: typeof LayoutRegisterRouteWithChildren
    parentRoute: typeof LayoutRouteWithChildren
  }
  '/api/auth/login': {
    id: '/api/auth/login'
    path: '/api/auth/login'
    fullPath: '/api/auth/login'
    preLoaderRoute: typeof ApiAuthLoginRouteWithChildren
    parentRoute: typeof rootRoute
  }
  '/api/auth/logout': {
    id: '/api/auth/logout'
    path: '/api/auth/logout'
    fullPath: '/api/auth/logout'
    preLoaderRoute: typeof ApiAuthLogoutRouteWithChildren
    parentRoute: typeof rootRoute
  }
  '/api/auth/me': {
    id: '/api/auth/me'
    path: '/api/auth/me'
    fullPath: '/api/auth/me'
    preLoaderRoute: typeof ApiAuthMeRouteWithChildren
    parentRoute: typeof rootRoute
  }
  '/api/auth/profile': {
    id: '/api/auth/profile'
    path: '/api/auth/profile'
    fullPath: '/api/auth/profile'
    preLoaderRoute: typeof ApiAuthProfileRouteWithChildren
    parentRoute: typeof rootRoute
  }
  '/api/auth/register': {
    id: '/api/auth/register'
    path: '/api/auth/register'
    fullPath: '/api/auth/register'
    preLoaderRoute: typeof ApiAuthRegisterRouteWithChildren
    parentRoute: typeof rootRoute
  }
}

export interface FileRoutesByFullPath {
  '/': {
    id: '/'
    path: '/'
    fullPath: '/'
    preLoaderRoute: typeof LayoutIndexRouteWithChildren
    parentRoute: typeof LayoutRouteWithChildren
  }
  '/dashboard': {
    id: '/dashboard'
    path: '/dashboard'
    fullPath: '/dashboard'
    preLoaderRoute: typeof LayoutDashboardRouteWithChildren
    parentRoute: typeof LayoutRouteWithChildren
  }
  '/login': {
    id: '/login'
    path: '/login'
    fullPath: '/login'
    preLoaderRoute: typeof LayoutLoginRouteWithChildren
    parentRoute: typeof LayoutRouteWithChildren
  }
  '/profile': {
    id: '/profile'
    path: '/profile'
    fullPath: '/profile'
    preLoaderRoute: typeof LayoutProfileRouteWithChildren
    parentRoute: typeof LayoutRouteWithChildren
  }
  '/register': {
    id: '/register'
    path: '/register'
    fullPath: '/register'
    preLoaderRoute: typeof LayoutRegisterRouteWithChildren
    parentRoute: typeof LayoutRouteWithChildren
  }
  '/api/auth/login': {
    id: '/api/auth/login'
    path: '/api/auth/login'
    fullPath: '/api/auth/login'
    preLoaderRoute: typeof ApiAuthLoginRouteWithChildren
    parentRoute: typeof rootRoute
  }
  '/api/auth/logout': {
    id: '/api/auth/logout'
    path: '/api/auth/logout'
    fullPath: '/api/auth/logout'
    preLoaderRoute: typeof ApiAuthLogoutRouteWithChildren
    parentRoute: typeof rootRoute
  }
  '/api/auth/me': {
    id: '/api/auth/me'
    path: '/api/auth/me'
    fullPath: '/api/auth/me'
    preLoaderRoute: typeof ApiAuthMeRouteWithChildren
    parentRoute: typeof rootRoute
  }
  '/api/auth/profile': {
    id: '/api/auth/profile'
    path: '/api/auth/profile'
    fullPath: '/api/auth/profile'
    preLoaderRoute: typeof ApiAuthProfileRouteWithChildren
    parentRoute: typeof rootRoute
  }
  '/api/auth/register': {
    id: '/api/auth/register'
    path: '/api/auth/register'
    fullPath: '/api/auth/register'
    preLoaderRoute: typeof ApiAuthRegisterRouteWithChildren
    parentRoute: typeof rootRoute
  }
}

export interface FileRoutesByTo {
  '/': {
    id: '/'
    path: '/'
    fullPath: '/'
    preLoaderRoute: typeof LayoutIndexRouteWithChildren
    parentRoute: typeof LayoutRouteWithChildren
  }
  '/dashboard': {
    id: '/dashboard'
    path: '/dashboard'
    fullPath: '/dashboard'
    preLoaderRoute: typeof LayoutDashboardRouteWithChildren
    parentRoute: typeof LayoutRouteWithChildren
  }
  '/login': {
    id: '/login'
    path: '/login'
    fullPath: '/login'
    preLoaderRoute: typeof LayoutLoginRouteWithChildren
    parentRoute: typeof LayoutRouteWithChildren
  }
  '/profile': {
    id: '/profile'
    path: '/profile'
    fullPath: '/profile'
    preLoaderRoute: typeof LayoutProfileRouteWithChildren
    parentRoute: typeof LayoutRouteWithChildren
  }
  '/register': {
    id: '/register'
    path: '/register'
    fullPath: '/register'
    preLoaderRoute: typeof LayoutRegisterRouteWithChildren
    parentRoute: typeof LayoutRouteWithChildren
  }
  '/api/auth/login': {
    id: '/api/auth/login'
    path: '/api/auth/login'
    fullPath: '/api/auth/login'
    preLoaderRoute: typeof ApiAuthLoginRouteWithChildren
    parentRoute: typeof rootRoute
  }
  '/api/auth/logout': {
    id: '/api/auth/logout'
    path: '/api/auth/logout'
    fullPath: '/api/auth/logout'
    preLoaderRoute: typeof ApiAuthLogoutRouteWithChildren
    parentRoute: typeof rootRoute
  }
  '/api/auth/me': {
    id: '/api/auth/me'
    path: '/api/auth/me'
    fullPath: '/api/auth/me'
    preLoaderRoute: typeof ApiAuthMeRouteWithChildren
    parentRoute: typeof rootRoute
  }
  '/api/auth/profile': {
    id: '/api/auth/profile'
    path: '/api/auth/profile'
    fullPath: '/api/auth/profile'
    preLoaderRoute: typeof ApiAuthProfileRouteWithChildren
    parentRoute: typeof rootRoute
  }
  '/api/auth/register': {
    id: '/api/auth/register'
    path: '/api/auth/register'
    fullPath: '/api/auth/register'
    preLoaderRoute: typeof ApiAuthRegisterRouteWithChildren
    parentRoute: typeof rootRoute
  }
}

export interface FileRoutesById {
  __root__: {
    id: '__root__'
    path: ''
    fullPath: ''
    preLoaderRoute: typeof rootRoute
    parentRoute: never
  }
  '/_layout': {
    id: '/_layout'
    path: '/'
    fullPath: '/'
    preLoaderRoute: typeof LayoutRouteWithChildren
    parentRoute: typeof rootRoute
  }
  '/': {
    id: '/'
    path: '/'
    fullPath: '/'
    preLoaderRoute: typeof LayoutIndexRouteWithChildren
    parentRoute: typeof LayoutRouteWithChildren
  }
  '/dashboard': {
    id: '/dashboard'
    path: '/dashboard'
    fullPath: '/dashboard'
    preLoaderRoute: typeof LayoutDashboardRouteWithChildren
    parentRoute: typeof LayoutRouteWithChildren
  }
  '/login': {
    id: '/login'
    path: '/login'
    fullPath: '/login'
    preLoaderRoute: typeof LayoutLoginRouteWithChildren
    parentRoute: typeof LayoutRouteWithChildren
  }
  '/profile': {
    id: '/profile'
    path: '/profile'
    fullPath: '/profile'
    preLoaderRoute: typeof LayoutProfileRouteWithChildren
    parentRoute: typeof LayoutRouteWithChildren
  }
  '/register': {
    id: '/register'
    path: '/register'
    fullPath: '/register'
    preLoaderRoute: typeof LayoutRegisterRouteWithChildren
    parentRoute: typeof LayoutRouteWithChildren
  }
  '/api/auth/login': {
    id: '/api/auth/login'
    path: '/api/auth/login'
    fullPath: '/api/auth/login'
    preLoaderRoute: typeof ApiAuthLoginRouteWithChildren
    parentRoute: typeof rootRoute
  }
  '/api/auth/logout': {
    id: '/api/auth/logout'
    path: '/api/auth/logout'
    fullPath: '/api/auth/logout'
    preLoaderRoute: typeof ApiAuthLogoutRouteWithChildren
    parentRoute: typeof rootRoute
  }
  '/api/auth/me': {
    id: '/api/auth/me'
    path: '/api/auth/me'
    fullPath: '/api/auth/me'
    preLoaderRoute: typeof ApiAuthMeRouteWithChildren
    parentRoute: typeof rootRoute
  }
  '/api/auth/profile': {
    id: '/api/auth/profile'
    path: '/api/auth/profile'
    fullPath: '/api/auth/profile'
    preLoaderRoute: typeof ApiAuthProfileRouteWithChildren
    parentRoute: typeof rootRoute
  }
  '/api/auth/register': {
    id: '/api/auth/register'
    path: '/api/auth/register'
    fullPath: '/api/auth/register'
    preLoaderRoute: typeof ApiAuthRegisterRouteWithChildren
    parentRoute: typeof rootRoute
  }
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashboard' | '/login' | '/profile' | '/register' | '/api/auth/login' | '/api/auth/logout' | '/api/auth/me' | '/api/auth/profile' | '/api/auth/register'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/login' | '/profile' | '/register' | '/api/auth/login' | '/api/auth/logout' | '/api/auth/me' | '/api/auth/profile' | '/api/auth/register'
  id: '__root__' | '/_layout' | '/' | '/dashboard' | '/login' | '/profile' | '/register' | '/api/auth/login' | '/api/auth/logout' | '/api/auth/me' | '/api/auth/profile' | '/api/auth/register'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  ApiAuthRegisterRoute: typeof ApiAuthRegisterRouteWithChildren
  ApiAuthLoginRoute: typeof ApiAuthLoginRouteWithChildren
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRouteWithChildren
  ApiAuthMeRoute: typeof ApiAuthMeRouteWithChildren
  ApiAuthProfileRoute: typeof ApiAuthProfileRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  ApiAuthRegisterRoute: ApiAuthRegisterRouteWithChildren,
  ApiAuthLoginRoute: ApiAuthLoginRouteWithChildren,
  ApiAuthLogoutRoute: ApiAuthLogoutRouteWithChildren,
  ApiAuthMeRoute: ApiAuthMeRouteWithChildren,
  ApiAuthProfileRoute: ApiAuthProfileRouteWithChildren,
}

export const routeTree = rootRouteWithChildren

/* prettier-ignore-end */
